name: Test Quarkus Backend

on:
  push:

env:
  QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://localhost:5432/quarkus

jobs:
  build:
    runs-on: docker

    services:
      postgres:
        image: postgres:17-alpine@sha256:dc17045ccfd343b49600570ea734b9c4991cf1c3f3302e67df51e3b402dd55c4
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: quarkus
          POSTGRES_DB: quarkus
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: https://github.com/actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run maven test
        run: ./mvnw clean test -fae

      - name: Run maven package
        run: ./mvnw package -Dquarkus.container-image.push=false
