name: Test Quarkus Backend

on:
  push:

jobs:
  build:
    runs-on: docker

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: https://github.com/actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Run maven test
        run: ./mvnw clean test -fae

      - name: Run maven package
        run: ./mvnw package -Dquarkus.container-image.push=false
