name: Test Quarkus Backend

on:
  push:
    branches:
      - main
      - cicd
    paths:
      - 'api/**'
      - '.forgejo/workflows/backend.yaml'

env:
  QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://localhost:5432/quarkus

jobs:
  build:
    runs-on: docker

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: quarkus
          POSTGRES_DB: quarkus
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
              
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: https://github.com/actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run maven test
        working-directory: api
        run: ./mvnw clean test -fae

      - name: Run maven package
        working-directory: api
        run: ./mvnw package -Dquarkus.container-image.push=false